PR Featurebranch/sprint3 to Dev
Training10x/training-batch14-customer-service-keertana pull request #9
Opened 2024-12-13 17:27 UTC by padmanabhamsaikeertana

2024-12-14 20:29 UTC, sreejanomula commented on customer_service/src/main/java/com/example/customer_service/mapper/CustomerMapper.java
when i compared it i saw that mapper class  is deleted

2024-12-14 20:31 UTC, sreejanomula commented on customer_service/src/test/java/com/example/customer_service/mapper/CustomerServiceMapperTest.java
when i compared it i saw that mappertest class is deleted

2024-12-14 22:12 UTC, padmanabhamsaikeertana commented on customer_service/src/main/java/com/example/customer_service/mapper/CustomerMapper.java
I have removed my mapper class and created a new mapper interface

2024-12-14 22:12 UTC, padmanabhamsaikeertana commented on customer_service/src/test/java/com/example/customer_service/mapper/CustomerServiceMapperTest.java
I have removed my mapper class test and created a new mapper interface test

2024-12-16 06:11 UTC, sreejanomula requested changes
can you update the changes

2024-12-16 18:53 UTC, sreejanomula approved these changes

2024-12-16 18:56 UTC, merged